Algoritmo "exerc22-maior-menor-10"
// Aula        : Lógica de programação com Visual G
// Professor   : Jailson Costa dos Santos
// Descrição   : Lê um número inteiro e diz se é maior ou menor que 10
// Autor(a)    : Renan de Castro Teixeira
// Data atual  : 29/03/2026
Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um número inteiro para saber se é maior ou menor que 10: ")
   leia(numero)

   se (numero > 10) entao
      escreva("É MAIOR QUE 10!")
   senao
      escreva("NÃO É MAIOR QUE 10!")
   fimse

Fimalgoritmo