Algoritmo "area-quadrado"
// Aula        : Lógica de programação com Visual G
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula área do quadrado
// Autor(a)    : Renan de Castro Teixeira
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
area, lado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite o lado do quadrado para calcularmos a área: ")
leia (lado)

area <- lado * lado

escreva ("A area do quadrado é: ",area)

Fimalgoritmo