Algoritmo "converte-metros-em-centimetros"
// Aula        : Lógica de programação com Visual G
// Professor   : Jailson Costa dos Santos
// Descrição   : Converte um valor de metros em centímetros
// Autor(a)    : Renan de Castro Teixeira
// Data atual  : 20/03/2026
const

multiplicador = 100

Var
// Seção de Declarações das variáveis 
metros: real
//multiplicador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

//multiplicador <- 100

escreva("Digite um valor em metros para conversão em centímetros: ")
leia(metros)

escreva(metros,"m são equivalentes a", metros * multiplicador,"cm")

Fimalgoritmo