Algoritmo "subtracao"
// Aula        : Lógica de programação com Visual G
// Professor   : Jailson Costa dos Santos
// Descrição   : Faz a subtração de dois valores e exibe resultado
// Autor(a)    : Renan de Castro Teixeira
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
n1, n2, r: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Faz a subtração de dois valores. Digite o primeiro valor: ")
Leia (n1)

Escreva ("Digite o segundo valor: ")
Leia (n2)

r <- n1 - n2

Escreva ("A subtração de", n1 ," -", n2 ," é: ", r)
Fimalgoritmo