Algoritmo "exemploTomadaDecisaoSimples"
// Aula        : Lógica de programação com Visual G
// Professor   : Jailson Costa dos Santos
// Descrição   : Exemplo de tomada de decisão simples com "Se"
// Autor(a)    : Renan de Castro Teixeira
// Data atual  : 23/03/2026
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

       Escreval("Programa de tomada de decisão simples")
       Escreval("Digite um valor:")
       Leia(numero)
       Se numero > 10 então
       Escreval("Número digitado é maior que 10!")
       Fimse

Fimalgoritmo