Algoritmo "multiplicacao"
// Aula        : Lógica de programação com Visual G
// Professor   : Jailson Costa dos Santos
// Descrição   : Multiplica dois valores e exibe o resultado
// Autor(a)    : Renan de Castro Teixeira
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis
n1, n2 ,r: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Multiplicação de dois valores, digite o primeiro número: ")
Leia(n1)

Escreva ("Digite o segundo número: ")
Leia (n2)

r <- n1 * n2

Escreva ("O resultado da multiplicação de", n1 ," *", n2 ," é: ", r)

Fimalgoritmo