Algoritmo "exercicio1Parte1"
// Aula        : Lógica de programação com Visual G
// Professor   : Jailson Costa dos Santos
// Descrição   : Validação de nota: Leia a nota de um aluno em
// Cálculo 1. Se a nota for maior ou igual a 6.0, exiba "Aprovado".
// Autor(a)    : Renan de Castro Teixeira
// Data atual  : 09/04/2026
Var
   // Seção de Declarações das variáveis
   nota: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite sua nota de cálculo 1 para saber se está aprovado ou não: ")
   leia(nota)

   se nota >= 6 entao
      escreval("Aprovado.")
   fimse

Fimalgoritmo